name: Send-Telegram

on:
  workflow_dispatch:
  push:
    branches: [ telegram ]
    paths-ignore:
        - '**.md'
    schedule:
        - cron: '0 12 * * 1-5'

env:
  CI: true

jobs:

  build-ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Declarative Checkout SCM
        uses: actions/checkout@v3

      - name: SCM
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven

      - name: send telegram for standUp
        run: mvn clean verify -Dcucumber.filter.tags='@telegram-bot'